### ISSUE TITLE
Getting errors while installing the server

### ISSUE THREAD

**Issue by Zohaib75** [StrongKey/fido2#10]
can you please help me to install the server? currently the error is:

Creating 10M SKFS Internal Database....done
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands. 
Closest matching local command(s): 
    setup-local-dcom
    setup-ssh
    unset

any help would be appreciated!

**Comment by Kaeptenblaubaer** [comment]
What was the solution? I have the same problem, but not in every Environment.
