### ISSUE TITLE
Basic Java Sample error: relying party ID is not registrable domain suffix

### ISSUE THREAD

**Issue by ric-sapasap** [StrongKey/fido2#102]
**Describe the bug**
I deployed my own FIDO2 server (v4.4.0) and the basic java sample application. I just followed the installation guides for both, but I'm unable to register a test user using the provided HTML form.

![image](https://user-images.githubusercontent.com/52158902/113893956-1d0de480-97fa-11eb-945f-cfbda2dfabb1.png)

The server responded with an HTTP status code of 200, here is the response:
`{"Response":"{\"Response\":{\"rp\":{\"name\":\"FIDOServer\",\"id\":\"strongkey.com\"},\"user\":{\"name\":\"zxc\",\"id\":\"SLxGyzAzRXYq5AQ29cRu3jWVcl5HmKuWGiS-qcRiibw\",\"displayName\":\"qwe123\"},\"challenge\":\"VROJRlOZzf5F2rQFXusJIQ\",\"pubKeyCredParams\":[{\"type\":\"public-key\",\"alg\":-7},{\"type\":\"public-key\",\"alg\":-35},{\"type\":\"public-key\",\"alg\":-36},{\"type\":\"public-key\",\"alg\":-8},{\"type\":\"public-key\",\"alg\":-43},{\"type\":\"public-key\",\"alg\":-257},{\"type\":\"public-key\",\"alg\":-258},{\"type\":\"public-key\",\"alg\":-259},{\"type\":\"public-key\",\"alg\":-37},{\"type\":\"public-key\",\"alg\":-38},{\"type\":\"public-key\",\"alg\":-39}],\"excludeCredentials\":[],\"attestation\":\"direct\"}}","Message":"","Error":"False"}`

I have also tried doing this via command line but I had a weird error regarding SSL handshakes:

![image](https://user-images.githubusercontent.com/52158902/113895133-3ebb9b80-97fb-11eb-9cb8-f81ee19c5ad3.png)

Deployment OS: Amazon Linux 2
Client OS: Ubuntu 18.04
Browser: Chrome (v89), Firefox (v86)

Did I miss a step in the setup or did something wrong?

Please do tell if you need any more additional details.

Thanks in advance for the help!

**Comment by arshadnoor** [comment]
Your FQDN (fido2-test.api.ewallet.pearlpay.io) for the FIDO server does not match the RPID (strongkey.com) on the server's policy. This thread (https://github.com/StrongKey/fido2/issues/97)  provides the solution to change your RPID in the policy. Make sure you restart your FIDO server before attempting to register again.

**Comment by ric-sapasap** [comment]
Hi @arshadnoor, thanks for the quick reply. I followed the instructions on the thread you linked and it worked!

I saw on that thread that the RP should have been automatically changed during installation, is it still an open issue?

**Comment by arshadnoor** [comment]
You're welcome,  @ric-sapasap.

I have to review this with the engineering team. We will work on getting 
our repositories updated within the next week or two at the latest.

**Comment by ric-sapasap** [comment]
Copy that, thanks!
