### ISSUE TITLE
Can StrongKey support to be executed on RaspberryPi with ubuntu 18.04.2 ?

### ISSUE THREAD

**Issue by paulwang55** [StrongKey/fido2#11]
Hi,
According to the installation guide, strongkey support ubuntu 18.04 (x86_64). 

Can stronkey fido2 server be executed on RaspberryPi runnung with ubuntu 18.04.2. (https://wiki.ubuntu.com/ARM/RaspberryPi) ?

Or, stronkey has any plan to porting fido2 server running on arm architecture ( RaspberryPi).

Regards,

Paul Wang

**Comment by arshadnoor** [comment]
Hi Paul,

Thanks for your interest in our FIDO2 server.

Our server is written as a Java Enterprise Edition (JEE) application; so 
it can run on any platform on which the Payara4 Application Server 
<https://www.payara.fish/> runs.  Payara itself is a Java application, 
so it will run on any platform that the OpenJDK can be installed.  
Ubuntu for x86 definitely has a port of the OpenJDK, and we support that 
architecture.  What we do not know is if an OpenUDK exists for the ARM 
Cortex - although I suspect it does - and once installed, whether the 
stack will run on a 1GB Raspberry Pi 3B+.  (I'm assuming the 3 B+ is the 
fastest Pi out there until the 4 comes out).

You're welcome to test this and update us on what you learn. on this 
forum  If you get it working and provide the instructions, we'll be glad 
to validate the instructions, post it to our web-pages and attribute the 
contribution to you.

All the best,

Arshad

**Comment by push2085** [comment]
Hi @paulwang55,
Do you have any additional questions on this? If not I will close the issue this week.

Thank you

**Comment by paulwang55** [comment]
Hi,

I have question for deploying StrongKey FIDO Server. I get the following error message.

[2019-08-13T11:36:59.018+0800] [Payara 4.1] [嚴重] [] [org.eclipse.persistence.session./file:/usr/local/strongkey/payara41/glassfish/domains/domain1/applications/fidoserver/replicationEJB-4.2.0_jar/_strongkeylitePU.ejb] [tid: _ThreadID=46 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565667419018] [levelValue: 1000] [[

java.lang.UnsatisfiedLinkError: JNA native support (/com/sun/jna/linux-arm/libjnidispatch.so) not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:734)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:708)
        at com.sun.jna.Native.<clinit>(Native.java:127)
        at org.mariadb.jdbc.internal.util.PidFactory$CLibrary.<clinit>(PidFactory.java:112)


How can I solve this issue ? 

I almost complete the installation on Raspberry pi. This issue is the last step for installation.

Regards,

Paul Wang

**Comment by push2085** [comment]
Hi @paulwang55, 
I am not very familiar with the raspberry pi architecture but what I would try is to see if it's missing some install dependencies. 
If it's Ubuntu then try installing libjna-java library using apt get

The other suggestion I have is to look for the missing library or so file in the jre lib and if it doesn't exist try to find the right location and create a symlink to it in the right location.

**Comment by paulwang55** [comment]
Hi @push2085 ,

I follow your suggestion to install libjna-java library. It still receive the same error message --- >java.lang.UnsatisfiedLinkError: JNA native support (/com/sun/jna/linux-arm/libjnidispatch.so) not found in resource path.

Do you know where I can find the needed library ?

**Comment by paulwang55** [comment]
Hi @push2085 ,

After I execute "ln -s" to link libjnidispatch.system.so with libjnidispatch.so. I get the another error. The message is :

[2019-08-13T16:35:42.268+0800] [Payara 4.1] [嚴重] [] [org.eclipse.persistence.session./file:/usr/local/strongkey/payara41/glassfish/domains/domain1/applications/fidoserver/replicationEJB-4.2.0_jar/_strongkeylitePU.ejb] [tid: _ThreadID=50 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565685342268] [levelValue: 1000] [[

java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:135)

Do I link the wrong jar file ?

How can I solve this issue ?

**Comment by push2085** [comment]
Hi @paulwang55 ,
The symlink does look wrong so you can remove that. We do not use any specific JNA library so I cant give you a version number.

After you installed the jni java library, is there a way to reload library path on your RPI or did you just try to restart the server once?

**Comment by paulwang55** [comment]
Hi @push2085,

After I install Jin java library, I just cleanup strongkey installation using the script and reboot RPI. Then I just reninstall it again. If I don’t do the symlink, I will get the same error message. It can not find libjnidispatch.so file.

Do you have any further suggestion to solve it ?

**Comment by paulwang55** [comment]
Hi @push2085 ,

I change some configuration of my RPI. I get the new error message.

1. I am using openJDK 11 ( not openJDK 8)
2. I am using payara5 as my glassfish

I receive the following error message.
**Deploying StrongKey FidoServer ...
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands. 
Closest matching local command(s): 
    help

Command deploy failed.
Done!**


**Here is server log from my "domain1" :**

You can review the serverr.log from the following link.

How can I solve this issue ? 

I know the port 4848 that it existed before this error was issued.

I don't understand why this port  disappears.

[https://www.dropbox.com/s/40yiikoh4j0dfuo/server.log?dl=0]

[2019-08-14T15:10:50.303+0800] [Payara 5.192] [警告] [APPL-MSG-1000] [APPL] [tid: _ThreadID=56 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565766650303] [levelValue: 900] [[
  APPL-MSG-1000: Informational Message: Following encryption domains are disabled for network webservices: []]]

[2019-08-14T15:10:50.456+0800] [Payara 5.192] [警告] [REPL-MSG-4000] [REPL] [tid: _ThreadID=56 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565766650456] [levelValue: 900] [[
  REPL-MSG-4000: ZMQ Message: Replication is set to false; objects will NOT be replicated]]

[2019-08-14T15:10:52.473+0800] [Payara 5.192] [資訊] [] [org.glassfish.soteria.servlet.SamRegistrationInstaller] [tid: _ThreadID=56 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565766652473] [levelValue: 800] [[
  Initializing Soteria 1.1-b01 for context '/api']]

[2019-08-14T15:10:52.960+0800] [Payara 5.192] [資訊] [] [javax.enterprise.web] [tid: _ThreadID=56 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565766652960] [levelValue: 800] [[
  WebModule[/api] ServletContext.log():No Spring WebApplicationInitializer types detected on classpath]]

[2019-08-14T15:10:53.441+0800] [Payara 5.192] [資訊] [jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=56 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1565766653441] [levelValue: 800] [[
  正在初始化環境「/api」的 Mojarra 2.3.9.payara-p2]]

**Comment by paulwang55** [comment]
Hi, @push2085

What is the minimum RAM needed by Strongkey FIDO2 ? For RPI 3, it only has 1GB RAM. Is it possible to running StrongKey FIDO2 Server ?

**Comment by push2085** [comment]
We have always tested with a minimum of 4GB memory but there is no reason for it to not work on anything less that that (The performance will be slow though).

Regarding your previous error, sometimes glassfish does leave a zombie process running so I would say just restart the server and see everything comes back up again. If you are getting this error while running the install script, do the following:
1) run clean up script and make sure there are no errors
2) Run the following command to see if any processes are left over
shell> pf str
3) If you see any process owned by the strongkey user, kill them manually
shell> kill -9 <pid>
4) Now run the clean up script one more time to ensure there are no errors
5) Restart server,
6) Follow the process again and run install script

**Comment by paulwang55** [comment]
Hi @push2085,

We deploy on RPI's 3 b+ successfully. We find that RAM is an issue. That's why we  didn't deploy it successfuly yesterday.

I have another issue about  excuting "java -jar keymanager.jar" command.

Here is the message from my execution.

The warning message is a normal message or not.

I use "curl script" to test server and sample client. 

The responses are correct. 

java -jar keymanager.jar regeneratesigningkey /usr/local/strongkey/skfs/keystores/signingkeystore.bcfks /usr/local/strongkey/skfs/keystores/signingtruststore.bcfks Abcd1234!

**WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom (file:/usr/local/strongkey/keymanager/lib/bc-fips-1.0.1.jar) to method sun.security.jca.Providers.getSunProvider()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release**

**Comment by push2085** [comment]
Hi @paulwang55,
I am glad it worked on a rpi 3b+. Would it possible for you to give us all the steps that you had to perform out side of our install script so that we can have a log to help others in the community of they run into similar situations.

I will also re test on less memory and add that to the pre requisites but can you tell me how much memory does your new device have? (I am assuming 3 gb).

Regarding the warning, I have read on some bcfips forum that this is only a warning and started with jdk 9 and does not have a solution yet so I will see if I find anything but the command should have worked. Can you confirm if it actually changed the key?

**Comment by paulwang55** [comment]
Hi @push2085,

Yes, the key was regenerated. I have some question about the configuration of my.cnf.

Can we reduce the size of memory using by mariadb ? (Currently the configuration is 512M)

For the installation: 
1. You need to install mariadb-server outside. You also need to modify my.cnf.
2. You need to install openjdk-11-jdk & libjna-java before you start to excute install-skfs.sh
3. You also need to extend raspbian's swap to 2048 Bytes
4. You need to modify install-skfs.sh & cleanup.sh , glassfishd
5. You also need to download payara5

I can provide the modified script files. After I complete my document. It will take my time to prepare it.

I am sure that the 1GB RAM is not enough for StrongKey FIDO2.

**Comment by push2085** [comment]
Hi @paulwang55 
You can change the mysql memory if you want it to have a different value.
I am going to close this issue, but if you decide to contribute the document you created, you can reopen this issue or contact us for the same.
