### ISSUE TITLE
Relying party ID and Name values

### ISSUE THREAD

**Issue by ashutoshkumarmishra560** [StrongKey/fido2#128]
Hi,

While initiating pre-registration request (i.e /skfs/rest/preregister) below JSON is received in the response:

{"Response":{"rp":{"name":"FIDOServer","id":"strongkey.com"},"user":{"name":"spips1","id":"QmT9jk7ljIV7MIB1pq1cFlBG1Q6HO_duWOTQFzOuEsI","displayName":"spips1key"},"challenge":"Dmf8mPzZDmpdcXKzVBvFoQ","pubKeyCredParams":[{"type":"public-key","alg":-7},{"type":"public-key","alg":-35},{"type":"public-key","alg":-36},{"type":"public-key","alg":-8},{"type":"public-key","alg":-43},{"type":"public-key","alg":-257},{"type":"public-key","alg":-258},{"type":"public-key","alg":-259},{"type":"public-key","alg":-37},{"type":"public-key","alg":-38},{"type":"public-key","alg":-39}],"excludeCredentials":[],"attestation":"direct"}}

The "name" is FIDOServer and "id" is strongkey.com. 
From where these values are fetched and how can I change them?

**Comment by pattycakelol** [comment]
Hi @ashutoshkumarmishra560, 

The rp "name" and rp "id" can be configured in the base64 encoded policy found in the fido_policies table in the database. You can update it there and restart glassfish or use the skfsclient.jar to make policy changes.

**Comment by ashutoshkumarmishra560** [comment]
Thanks. After making the changes I am getting WIndows PIN prompt to enter my PIN. When I enter that why am I getting prompted to setup security key? It says setup your security key to sign in to ***lab.com as <username>. This request comes from Chrome/Firefox. At present the code is invoking /skfs/rest calls.
However when I try the same via /basicserver WAR file, registration using Windows PIN works as expected.
I am using Win 10 home edition.

**Comment by ashutoshkumarmishra560** [comment]
Issue is resolved. The /register call was being made twice. I corrected the same and now flow works as expected. Thanks for the response.
