### ISSUE TITLE
Fido2 Server is failing

### ISSUE THREAD

**Issue by ankushpatel120** [StrongKey/fido2#136]
Unable to establish connection with the Fido2 server.

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
callserver result=>
SKFS pre-reg response: 
Jun 14, 2021 7:30:09 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherservlet] in context with path [/cipa] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Not a JSON Object: null] with root cause
java.lang.IllegalStateException: Not a JSON Object: null

Getting this error even after having a valid certificate .

**Comment by DavidCBeach** [comment]
@ankushpatel120 

Can you please provide additional logs for the error.
1. In a terminal sign in as strongkey user: 
$> su - strongkey
2. Tail the SKFS logs:
$> tsl 
3. Run your process
4. Reply with the error you see in the logs along with the the preceding log entries.

**Comment by ankushpatel120** [comment]
[strongkey@fido2 ~]$ tsl

[2021-06-15T10:03:18.277+0000] [Payara 5.2020.7] [INFO] [jsf.config.listener.version] [javax.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=97 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1623751398277] [levelValue: 800] [[
  Initializing Mojarra |version.string| for context '/replicationWAR']]

[2021-06-15T10:03:18.388+0000] [Payara 5.2020.7] [INFO] [AS-WEB-GLUE-00172] [javax.enterprise.web] [tid: _ThreadID=97 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1623751398388] [levelValue: 800] [[
  Loading application [fidoserver#replicationWAR-4.3.0.war] at [/replicationWAR]]]

[2021-06-15T10:03:18.698+0000] [Payara 5.2020.7] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=97 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1623751398698] [levelValue: 800] [[
  fidoserver was successfully deployed in 21,090 milliseconds.]]


these are the server logs from fido2 server after performing the process 

and the below logs are my local code logs 

POST https://fido2.ilantusdemo.com:8181/skfs/rest/preregister HTTP/1.1
callserver request=>POST https://fido2.ilantusdemo.com:8181/skfs/rest/preregister HTTP/1.1
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
callserver result=>
SKFS pre-reg response: 
Jun 15, 2021 4:39:06 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherservlet] in context with path [/cipa] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Not a JSON Object: null] with root cause
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.cipa.controller.MyController.fidoPreregister(MyController.java:44)

**Comment by push2085** [comment]
Hi @ankushpatel120 ,

The error that is being displayed "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target" means that you application is not able to find the path to the right certificate for the FIDO server that you have installed [https://fido2.ilantusdemo.com:8181].

If this is a java application, it is possible that it was not imported to the truststore or it could have been imported to the wrong truststore as multiple java version could have been installed.

The same applies for any other programming language.

Thank you

**Comment by ankushpatel120** [comment]
I checked thoroughly but I have only a single java version installed on my Fido2 server but I am facing the same issue SSL Handshake exception. Do we have to add an SSL certificate to the payara5 glassfish server manually or it is installed at the time of running the install-skfs.sh.

**Comment by ankushpatel120** [comment]
Can anyone please help Where can I collect the fido2 certificate on the server end?

**Comment by push2085** [comment]
Hi @ankushpatel120 ,
The FIDO server will automatically install the certificate in payara truststore during the install. The error you saw is from the client side so I would suggest trying out the java command line client from the client device and solve the client machine problem of not identifying the certificate.

Command line (https://github.com/StrongKey/fido2/tree/master/server/skfsclient) client can be downloaded with the zip.

When you run the java client manually, use the following option to specify the truststore file that java should use. 
**-Djavax.net.ssl.trustStore=<PATH to truststore>** 

Let us know if the command line works from the client machine and we can go from there.

Thank you
Pushkar
