### ISSUE TITLE
FIDO2 Server API version

### ISSUE THREAD

**Issue by GramThanos** [StrongKey/fido2#137]
I can see that the "FIDO2 Server API" changed a bit.

Is there anything that we can check to be able to track changes (something like a version) or we should expect posible changes upon every release of the FIDO2 server?

Currently I can see that although there are changes, the version was not changed.

I am asking this because I want to know how to maintain an SDK I developed for StrongKey FIDO2 Server (https://github.com/GramThanos/StrongMonkey). If the API versions is not trusted for this, I will have to maintain a compatibility table between my SDK version and the FIDO Server's version instead.

Thank you in advance.

**Comment by push2085** [comment]
Hi @GramThanos 

At this moment, we have release notes that has the API input request change documented. In the future we will think about an additional way to represent this.

We will also update the master with a release notes as well but here it is for now
https://github.com/StrongKey/fido2/blob/docker/docs/Release_Notes.pdf
