### ISSUE TITLE
Installation Guide Linux

### ISSUE THREAD

**Issue by felipejesuszup** [StrongKey/fido2#143]
I'm using the docs/Installation_Guide_Linux.md installation process but I can't do the guide because I have an aws rds database and the guide process is separated and makes the replication. I tried another process is to upload the fido server in two vm and each one using the same rds and I put a load balance in front of the vm, but I'm having a cache problem because when a request is made to a server and then it is played on another Due to the algorithm the process fails because it has previous data from the request that you use. I would like to help resolve this.

**Comment by pattycakelol** [comment]
Hi @felipejesuszup,

At the moment we have two tested configurations regarding database setup:
1. Local database in vm through the docs/Installation_Guide_Linux.md. [In a cluster](https://github.com/StrongKey/fido2/blob/master/docs/Clustering_Guide_Linux.md), each vm has its own database that replicates to the local databases of every other vm in the cluster.
2. External database with [docker instance setup](https://github.com/StrongKey/fido2/tree/master/docker). In this configuration, each container is connected to the same external database.

Regarding your load balancer cache issue, here are some possible issues that you may be facing:
1. Connectivity between the vms may not be set up correctly, please check step 3c in the [clustering guide](https://github.com/StrongKey/fido2/blob/master/docs/Clustering_Guide_Linux.md#cluster-setup) to make sure replication ports on the vms are open to each other.
2. There is a property in the clustering guide that allows for replication in step 4b. Ensure that this property is set on all clustered vms.
3. You may be sending a register request too soon after a preregister request, such that the preregister request does not have enough time to fully process. If this is the case, try putting a sleep between the preregister and register requests.

If you still have issues with this, could you provide the glassfish logs for the error that occurs?

**Comment by felipejesuszup** [comment]
Hi pattycakelol, 

thanks for the quick reply. Regarding the settings is ok, in my use case I have to have a single bank for the two vm. I'm going to test the preregister request time issue. Regarding the docker I tested it but all the script is for version 4.4.1 and the one that my company approved was 4.3.0 I saw that a lot had changed.

**Comment by arshadnoor** [comment]
Hi Felipe,

You should consider going with 4.4.1 if you can.

Version 4.4 added some very cool new features: Apple Attestation, SSO 
with JWS based JWT, and an Android library for native RCA apps in 
Android, including Transaction Authorization with FIDO digital 
signatures. 4.4.1 adds one new webservice related to using Active 
Directory domain UPNs as SKFS userIds; plus a bug-fix for time-outs 
between preregister/register, preauthenticate/authenticate and 
preauthorize/authorize webservices across a cluster.

So, I would definitely encourage going forward with the latest release, 
if possible.

**Comment by felipejesuszup** [comment]
Hi Arshad, Thanks for the answer! I will try to migrate.
