### ISSUE TITLE
Help with Basic Java Sample Demo 

### ISSUE THREAD

**Issue by wsideveloper** [StrongKey/fido2#169]
I am able to install a SKFS server with my internet domain. I can do a ping to my server too:
java -jar skfsclient.jar P https://<mydomain>:8181 1 REST PASSWORD svcfidouser Abcd1234!

However when I install the Basic Java Sample Demo and launch it to my server https://<mydomain>:8181//basicdemo/

I get this error when I do a register: 
SecurityError: The relying party ID is not a registrable domain suffix of, nor equal to the current domain.

Is there configuration needed on the server to add my domain? Any pointer?

**Comment by arshadnoor** [comment]
You closed the issued; did you figure out the problem?
