### ISSUE TITLE
FIDO docker external LDAP connection fail

### ISSUE THREAD

**Issue by prathapcoder** [StrongKey/fido2#179]
**  LDAP connection fail due IP address not changing **

*base64-input.sh:*
LDAP_URLPORT='ldap://192.168.226.129:1389'
LDAP_TYPE='LDAP'
LDAP_BINDDN='cn=Directory Manager'

** server.log:*
ldape.cfg.property.service.ce.ldap.ldapurl: ldap://localhost:1389
it taking defualt localhost instead of given ip 192.168.226.129.

Please resolve my issue.
Thank you.

**Comment by prathapcoder** [comment]
> Hi @prathapcoder, Could you take a look at the ldape.cfg.property.service.ce.ldap.ldapurl property in your /usr/local/strongkey/skce/etc/skce-configuration.properties file? The value of that property should be changed in the entrypoint script, but if it is set to localhost then something may have gone wrong when running the entrypoint script during container creation.

skce-configuration.properties file not created in this (/usr/local/strongkey/skce/etc/) location.
Even i comment the following lines in entrypoint.sh file. please check.

**entrypoint.sh**
#rm -f $STRONGKEY_HOME/appliance/etc/appliance-configuration.properties $STRONGKEY_HOME/skce/etc/skce-configuration.properties $STRONGKEY_HOME/skfs/etc/skfs-configuration.properties

**Comment by pattycakelol** [comment]
Hi @prathapcoder,

In [lines 61-70 of the entrypoint script](https://github.com/StrongKey/fido2/blob/master/docker/entrypoint.sh#L61-L70), these values should be set in a newly created /usr/local/strongkey/skce/etc/skce-configuration.properties.
Try adding some prints in your entrypoint and remove the "-d" option from your docker run command to run the container in foreground mode to see your entrypoint prints.

**Comment by prathapcoder** [comment]
> Hi @prathapcoder,
> 
> In [lines 61-70 of the entrypoint script](https://github.com/StrongKey/fido2/blob/master/docker/entrypoint.sh#L61-L70), these values should be set in a newly created /usr/local/strongkey/skce/etc/skce-configuration.properties. Try adding some prints in your entrypoint and remove the "-d" option from your docker run command to run the container in foreground mode to see your entrypoint prints.

yes i added some prints (echo command) and removed "-d" option, but those line not printingl.
I added echo lines in my *entrypoint.h* file.
echo "skce-configuration.........."
cat >> $STRONGKEY_HOME/skce/etc/skce-configuration.properties <<- EOFSKCECONF
ldape.cfg.property.service.ce.ldap.ldapurl=$LDAP_URLPORT
ldape.cfg.property.service.ce.ldap.ldaptype=$LDAP_TYPE
ldape.cfg.property.service.ce.ldap.ldapbinddn=$LDAP_BINDDN
ldape.cfg.property.service.ce.ldap.ldapbinddn.password=$LDAP_PASS
ldape.cfg.property.service.ce.ldap.ldapdnprefix=cn=
ldape.cfg.property.service.ce.ldap.ldapdnsuffix=$LDAP_DNSUFFIX
ldape.cfg.property.service.ce.ldap.basedn=$LDAP_BASEDN
ldape.cfg.property.service.ce.ldap.ldapgroupsuffix=$LDAP_GROUPSUFFIX
EOFSKCECONF
echo "LDAP URL"
echo $LDAP_URLPORT

**Comment by pattycakelol** [comment]
Hi @prathapcoder,

Have you made any changes to your dockerfile?
If your echo commands are not running then this may be an issue with bash or a missing entrypoint script within the container.

Try getting using a terminal within the container and checking to see if the entrypoint is there.
```
$> [sudo] docker exec -it <CONTAINER-ID> /bin/bash
```
