### ISSUE TITLE
maven build fido server failed due to com.strongkey:fido2mds:jar:4.4.0 not found

### ISSUE THREAD

**Issue by prathapcoder** [StrongKey/fido2#180]
** Maven build failed**
while building project from source code getting dependencies error.

**command**
*mvn install*
after executing above command below error getting.

Failed to execute goal on project fidoserverbeans: Could not resolve dependencies for project com.strongkey:fidoserverbeans:ejb:4.4.0: Could not find artifact com.strongkey:fido2mds:jar:4.4.0 in central (https://repo.maven.apache.org/maven2)

**Comment by pattycakelol** [comment]
Hi @prathapcoder,

You can find the dependency"fido2mds-4.4.0.jar" when extracting the distirbution [fido2server-v4.4.3-dist.tgz](https://github.com/StrongKey/fido2/blob/master/fido2server-v4.4.3-dist.tgz) and in the unzipped fidoserver.ear's lib/ directory.

**Comment by prathapcoder** [comment]
> Hi @prathapcoder,
> 
> You can find the dependency"fido2mds-4.4.0.jar" when extracting the distirbution [fido2server-v4.4.3-dist.tgz](https://github.com/StrongKey/fido2/blob/master/fido2server-v4.4.3-dist.tgz) and in the unzipped fidoserver.ear's lib/ directory.

how to add fido2mds-4.4..0.jar file in local maven repository through command line.

**Comment by pattycakelol** [comment]
Hi @prathapcoder,

Running:
```
mvn install:install-file "-Dfile=fido2mds-4.4.0.jar" "-DgroupId=com.strongkey" "-DartifactId=fido2mds" "-Dversion=4.4.0" "-Dpackaging=jar" "-DgeneratePom=true"
```
should add fido2mds-4.4.0.jar to your local maven repository. You will be able to find it in your .m2 directory once installed.

**Comment by prathapcoder** [comment]
> Hi @prathapcoder,
> 
> Running:
> 
> ```
> mvn install:install-file "-Dfile=fido2mds-4.4.0.jar" "-DgroupId=com.strongkey" "-DartifactId=fido2mds" "-Dversion=4.4.0" "-Dpackaging=jar" "-DgeneratePom=true"
> ```
> 
> should add fido2mds-4.4.0.jar to your local maven repository. You will be able to find it in your .m2 directory once installed.

after executing above command and *maven install* command 
following error getting:


[INFO] Reactor Summary for fidoserver 4.4.0:
[INFO] 
[INFO] fidoserver ......................................... SUCCESS [  0.389 s]
[INFO] crypto ............................................. SUCCESS [  8.395 s]
[INFO] common ............................................. SUCCESS [  3.611 s]
[INFO] authenticationBeans ................................ SUCCESS [  0.641 s]
[INFO] fidoserverbeans .................................... FAILURE [  3.436 s]
[INFO] skfe ............................................... SKIPPED
[INFO] keymanager ......................................... SKIPPED
[INFO] skfs ............................................... SKIPPED
[INFO] FIDO2Simulator ..................................... SKIPPED
[INFO] skfsclient ......................................... SKIPPED
[INFO] fidoserverEAR ...................................... SKIPPED
[INFO] FIDO2JWTVerify ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.909 s
[INFO] Finished at: 2022-03-08T18:31:04-08:00
[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project fidoserverbeans: Compilation failure: Compilation failure: 
[ERROR] /home/tsip/fido/docker/fido2/server/fidoserverbeans/src/main/java/com/strongkey/skfs/utilities/SKCEReturnObject.java:[12,24] package javax.activation does not exist
[ERROR] /home/tsip/fido/docker/fido2/server/fidoserverbeans/src/main/java/com/strongkey/skfs/utilities/SKCEReturnObject.java:[46,13] cannot find symbol
[ERROR]   symbol:   class DataHandler
[ERROR]   location: class com.strongkey.skfs.utilities.SKCEReturnObject
[ERROR] /home/tsip/fido/docker/fido2/server/fidoserverbeans/src/main/java/com/strongkey/skfs/utilities/SKCEReturnObject.java:[64,5] cannot find symbol
[ERROR]   symbol:   class DataHandler
[ERROR]   location: class com.strongkey.skfs.utilities.SKCEReturnObject
[ERROR] /home/tsip/fido/docker/fido2/server/fidoserverbeans/src/main/java/com/strongkey/skfs/utilities/SKCEReturnObject.java:[68,35] cannot find symbol
[ERROR]   symbol:   class DataHandler
[ERROR]   location: class com.strongkey.skfs.utilities.SKCEReturnObject
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fidoserverbeans

**Comment by pattycakelol** [comment]
Hi @prathapcoder,

It is possible that you are receiving this error because you are building the SKFS with a Java version greater than 8.
At the moment, the SKFS only supports Java 8. Make sure your JAVA_HOME is set to a JDK 8 distribution before running a maven install on the SKFS.

**Comment by pleung-strongkey** [comment]
As of version 4.6.0, the SKFS now runs on JDK 11 by default.
