### ISSUE TITLE
Installation of SKFS on CentOS 8

### ISSUE THREAD

**Issue by ashutoshkumarmishra560** [StrongKey/fido2#185]
Hi,

I am trying to install SKFS v4.4.3 on CentOS 8 however openldap specific installation is not resulting in an error.  Below are the errors:

1. Failed to start slapd.service: Unit slapd.service not found.
cp: cannot stat '/usr/share/openldap-servers/DB_CONFIG.example': No such file or directory
chown: invalid user: ‘ldap:ldap’
./install-skfs.sh: line 394: /bin/ldapadd: No such file or directory
cp: cannot create regular file '/etc/openldap/schema/': No such file or directory
./install-skfs.sh: line 397: /bin/ldapadd: No such file or directory
./install-skfs.sh: line 409: /bin/ldapadd: No such file or directory

2.Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
Importing default users...
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

I think because of this my calls to /skfs/rest are failing as users are not present. Running manageSKFSCreds.sh is also complaining of openldap related  errors.
Do I have to separately setup openldap as I was under the impression that SKFS will automatically try to download and install the same.

Please suggest.

Thanks,
Ashutosh

**Comment by ashutoshkumarmishra560** [comment]
UPDATE: Tried the same on CentOS 7.9, almost all of the installation is successful except the deployment part with below error:

Deploying StrongKey FidoServer ... remote failure: Error occurred during deployment: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.payara-p3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Host 'idxlab.idx.com' is not allowed to connect to this MariaDB server
Error Code: 0. Please see server.log for more details.
Command deploy failed.

Because of the above error access /skfs/rest endpoint is resulting in 404

**Comment by khedrond** [comment]
Are you connecting to a remote database from the SKFS instance? Meaning, 
are the SKFS and database instance not running on the same machine?

If so, then you need to configure the connection to have remote access 
privileges:

https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/

**Comment by ashutoshkumarmishra560** [comment]
Never mind. I got it resolved. Thanks for your time. To your question yes both MariaDB and SKFS are on the same machine.

**Comment by sanudatta11** [comment]
@ashutoshkumarmishra560  how did you get this resolved?
