### ISSUE TITLE
how to use  the command  of ```java -jar keymanager.jar``` ?

### ISSUE THREAD

**Issue by paulwang55** [StrongKey/fido2#2]
Hi,

According to the installation guide, it suggest to change the default value of "signing and secret keys". 

Can you provide the sample instruction to use this command ? 
I use the following command to execute it.

java -jar keymanager.jar regeneratesigningkey /usr/local/strongkey/payara41/glassfish/domains/domain1/config/keystore.jks /usr/local/strongkey/payara41/glassfish/domains/domain1/config/cacerts.jks changeit```

It just reply me " > " symbol. I don't know how I can continue it.

**Comment by push2085** [comment]
Hi 
Sorry about the late response, somehow github did not send me a notification.
There are a couple of things i would like to point out here:
1) You are using the wrong keystore files (I just realized that the documentation is not clear and we will update it). The keymanager is intended to change the keystore and truststore located at "/usr/local/strongkey/skfs/keystores" location.

2) The password is wrong. The default password for the above mentioned keystore is "Abcd1234!"

Try the following command again and see if it works:

`java -jar keymanager.jar regeneratesigningkey /usr/local/strongkey/skfs/keystores/signingkeystore.bcfks /usr/local/strongkey/skfs/keystores/signingtruststore.bcfks Abcd1234!`

Hope this helps

**Comment by paulwang55** [comment]
Hi Pushkar Marathe,

Thanks for you assistance. This issue is sovled. I use your solution to solve it.

Regards,

Paul Wang
