### ISSUE TITLE
Android application for authenticator using flutter, ionic or react

### ISSUE THREAD

**Issue by adityarao1** [StrongKey/fido2#215]
Hi,

I'm creating one web application (pwa) using ionic and angular and that application has passwordless authentication enabled.
I want to convert the same to android mobile application.
Is it possible to use the same codebase (i.e what ionic is providing) for authenticator on mobile application also?

Thanks.

**Comment by StrongKeyAbhishek** [comment]
Hi Aditya,

To use platform authentication on mobile devices you will need to use native platform specific APIs. If you are making the application as a PWA(Progressive Web App) then it can only use browser WebAuthn APIs. If you want to make a native application with Platform Authentication capabilities you can use [StrongKey's FIDO2 Android library](https://github.com/StrongKey/fido2/tree/master/sampleapps/java/sacl) with [Ionic's](https://ionicframework.com/docs/native) or [Flutter's](https://docs.flutter.dev/development/platform-integration/platform-channels) platform specific code execution capability. We do not have a native StrongKey iOS FIDO2 Library yet but you can see our sample of Apple's FIDO2 API implementation [here](https://github.com/StrongKey/fido2/tree/master/sampleapps/swift/StrongKeyFIDODemo).

Regards,
Abhishek Saral

**Comment by StrongKeyAbhishek** [comment]
Hi Aditya, 
To use platform authentication on mobile devices you will need to use native platform specific APIs. If you are making the application as a PWA(Progressive Web App) then it can only use browser WebAuthn APIs. If you want to make a native application with Platform Authentication capabilities you can use [ https://github.com/StrongKey/fido2/tree/master/sampleapps/java/sacl | StrongKey's FIDO2 Android library ] with [ https://ionicframework.com/docs/native | Ionic's ] or [ https://docs.flutter.dev/development/platform-integration/platform-channels | Flutter's ] platform specific code execution capability. We do not have a native StrongKey iOS FIDO2 Library yet but you can see our sample of Apple's FIDO2 API implementation [ https://github.com/StrongKey/fido2/tree/master/sampleapps/swift/StrongKeyFIDODemo | here ] . 


From: "adityarao1" ***@***.***> 
To: "StrongKey/fido2" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, October 5, 2022 9:59:38 PM 
Subject: [StrongKey/fido2] Android application for authenticator using flutter, ionic or react (Issue #215) 





Hi, 

I'm creating one web application (pwa) using ionic and angular and that application has passwordless authentication enabled. 
I want to convert the same to android mobile application. 
Is it possible to use the same codebase (i.e what ionic is providing) for authenticator on mobile application also? 

Thanks.

**Comment by adityarao1** [comment]
Created new ticket https://github.com/StrongKey/fido2/issues/225. Hence closing this issue
