### ISSUE TITLE
Regenerate Signing Key - Corrupted

### ISSUE THREAD

**Issue by Mazecreator** [StrongKey/fido2#22]
I have completed the Linux Install of the FidoServer per the instructions.  I did need to eliminate the few lines from the install script as called out in #21 but it did succeed and made it through the 8 steps with no problems.  The noted at the bottom of the document talked about using "keymanager.jar" and from the instructions to regenerate the keys I figured it was this command line:

`java -jar keymanager.jar regeneratesigningkey /usr/local/strongkey/skfs/keystores/signingkeystore.bcfks /usr/local/strongkey/skfs/keystores/signingtruststore.bcfks ShaZam123`

I tried my new password rather than the default value first, but both fail the same way:

> Exception in thread "main" java.io.IOException: BCFKS KeyStore corrupted: MAC calculation failed.
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.verifyMac(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at Main.regeneratesigningkey(Main.java:120)
        at Main.main(Main.java:67)

Hopefully I guessed right with the command line.  Do I need to delete the existing files first to get this to work?

**Comment by push2085** [comment]
The password here should be the original default one
Example command: 
**java -jar keymanager.jar regeneratesigningkey signingkeystore.bcfks signingtruststore.bcfks Abcd1234!**

Output: 
**Regenerated signing key**

**Comment by Mazecreator** [comment]
Thanks, that worked with the password you listed.

The installation document wasn't clear if "ShaZam123" the default password for the keys.  It works with "Abcd1234!".  It might be good to add this to that section of the installation document, might be good to be able to set this password somewhere in the script prior to running if possible so this regeneration step isn't needed: 
https://github.com/StrongKey/fido2/blob/master/docs/Installation_Guide_Linux.md

I see a few lines in the "install-skfs.sh", but it wasn't clear they were used for the key stores. 

SERVICE_LDAP_BIND_PASS=Abcd1234!
SERVICE_LDAP_SVCUSER_PASS=Abcd1234!

**Comment by push2085** [comment]
Thank you @Mazecreator ,
We will update the document to reflect the default keystore password.
