### ISSUE TITLE
Authenticator is not Coming for Android application

### ISSUE THREAD

**Issue by adityarao1** [StrongKey/fido2#225]
I am creating native android application and using rest api.
During registration i'm calling preregistration and registration api. 
But the fido authenticator is not coming during registration process.
Please suggest a solution for this.

Below is the policy
{"FidoPolicy":{"name":"MinimalPolicy","copyright":"","version":"1.0","startDate":"1659696415","endDate":"1760103870871","system":{"requireCounter":"mandatory","integritySignatures":false,"userVerification":["required","preferred","discouraged"],"userPresenceTimeout":0,"allowedAaguids":["all"],"jwtKeyValidity":365,"jwtRenewalWindow":30,"transport":["usb","internal"]},"algorithms":{"curves":["secp256r1","secp384r1","secp521r1","curve25519"],"rsa":["RS256","RS384","RS512","PS256","PS384","PS384"],"signatures":["ES256","ES384","ES512","EdDSA","ES256K"]},"attestation":{"conveyance":["none","indirect","direct","enterprise"],"formats":["fido-u2f","packed","tpm","android-key","android-safetynet","apple","none"]},"registration":{"displayName":"required","attachment":["platform","cross-platform"],"discoverableCredential":["required","preferred","discouraged"],"excludeCredentials":"enabled"},"authentication":{"allowCredentials":"enabled"},"authorization":{"maxdataLength":256,"preserve":true},"rp":{"id":"compactidentityqa.com","name":"FIDOServer"},"extensions":{},"mds":{"authenticatorStatusReport":[{"status":"FIDO_CERTIFIED_L1","priority":"1","decision":"IGNORE"},{"status":"FIDO_CERTIFIED_L2","priority":"1","decision":"ACCEPT"},{"status":"UPDATE_AVAILABLE","priority":"5","decision":"IGNORE"},{"status":"REVOKED","priority":"10","decision":"DENY"}]},"jwt":{"algorithms":["ES256","ES384","ES521"],"duration":30,"required":["rpid","iat","exp","cip","uname","agent"],"signingCerts":{"DN":"CN=StrongKey KeyAppliance,O=StrongKey","certsPerServer":3}}}}

**Comment by arshadnoor** [comment]
What API are you using for the native Android app, Aditya? Are you using 
the Google FIDO2 API or StrongKey's Android Client Library (SACL)?

If you are using Google's API, then you have to ask Google for support; 
but if you are using SACL, take a look at the same app and applications 
to see how to make it work:

https://github.com/StrongKey/fido2/tree/master/sampleapps/java/sacl

You MUST have a mobile with Android 9 or greater for the SACL to work.
