### ISSUE TITLE
Installation error: opendjd.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by Canmmy** [StrongKey/fido2#24]
Hi,

I had install the server to Azure with Virtual Machine Ubuntu.
While I running the code sudo ./install-skfs.sh, I having issues as below:

```
Installing StrongKey FIDO2 Server (SKFS) ... Successful
Installing MariaDB... Successful
Installing Payara... Successful
Installing JDBC Driver... Successful
Installing OpenDJ... Successful
Job for opendjd.service failed because the control process exited with error code.
See "systemctl status opendjd.service" and "journalctl -xe" for details.

Unable to connect to the server at "fidovm" on port 4444

Importing default users... Connect Error
Result Code:  91 (Connect Error)
Successful
Creating 10M SKFS Internal Database...grep: /usr/local/strongkey/mariadb-10.2.13/log/mysqld-error.log: No such file or directory
.grep: /usr/local/strongkey/mariadb-10.2.13/log/mysqld-error.log: No such file or directory
```

I had search around but still can not solve the problem.
Can someone help?

**Comment by push2085** [comment]
Hi @Canmmy ,
Can you give us a little more information to debug the problem. 
1) What are the specs of the VM (Memory, HDD space , CPU, exact ubuntu version). Its quite possible that this vm is the minimal that Azure offers and does not have enough disk space or memory to run all these components. Run the following command and post that output as well:
shell> df -h

shell> vmstat -s | head

2) Can you also upload contents of **/var/log/messages** which may have some additional messages that might point to the problem.

**Comment by Canmmy** [comment]
Hi,

I had run the shell> df -h, here the infor:

> df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            940M     0  940M   0% /dev
> tmpfs           191M  668K  190M   1% /run
> /dev/sda1        29G  4.0G   25G  14% /
> tmpfs           953M     0  953M   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs           953M     0  953M   0% /sys/fs/cgroup
> /dev/sda15      105M  3.6M  101M   4% /boot/efi
> /dev/sdb1       3.9G   16M  3.7G   1% /mnt
> tmpfs           191M     0  191M   0% /run/user/1000

and vmstat -s | head
   

>    1951228 K total memory
>        280048 K used memory
>        209900 K active memory
>       1119848 K inactive memory
>        320380 K free memory
>         42516 K buffer memory
>       1308284 K swap cache
>             0 K total swap
>             0 K used swap
>             0 K free swap


I run the _systemctl status opendjd.service_ and here the log:

> ● opendjd.service - LSB: Init script for Opendj
>    Loaded: loaded (/etc/init.d/opendjd; generated)
>    Active: failed (Result: exit-code) since Mon 2020-02-10 02:17:39 UTC; 1min 34s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 10128 ExecStart=/etc/init.d/opendjd start (code=exited, status=127)

**Comment by push2085** [comment]
can you also send us contents of "/var/log/messages"

**Comment by Canmmy** [comment]
Hi,

I had solve the issue which some library is missing.

**Comment by silakr** [comment]
> Hi,
> 
> I had solve the issue which some library is missing.

Hi, I had encountered too.

How did you solve this issue?
