### ISSUE TITLE
What is the correct result to execute "curl -k https://localhost:8181/basicserver/application.wadl" ?

### ISSUE THREAD

**Issue by paulwang55** [StrongKey/fido2#3]
Hi,

I following the installation guide to install the  basicserver application. Then I execute "curl -k https://localhost:8181/basicserver/application.wadl" .

I receive the following result returing from my fido server.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Error report</title><style type="text/css"></style> </head><body><h1>HTTP Status 404 - Not Found</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Not Found</p><p><b>description</b>The requested resource is not available.</p><hr/></body></html>

I want to know this result correct or not. Because we get "HTTP Status 404 - Not Found". I don't understand it. During the installation, I did not receive any error message. 

I don't understand why I got "HTTP Status 404 - Not Found". When I execute "curl -k https://localhost:8181/basicserver/application.wadl".

Can someone know this issue and how to solve it ?

Best Regards,

Paul Wang

**Comment by push2085** [comment]
Hi 
We recently relocated our FIDO repository and merged a few repositories into one and in that merge the URL for the "application.wadl" has changed.
The new URL is : **https://localhost:8181/basicserver/fido2/application.wadl**
Run the curl command against this new URL and you should see the WADL file.

Thank you for catching this and I have already updated the documentation to reflect the change.

**Comment by paulwang55** [comment]
Hi Pushkar Marathe,

Thanks for your assistance. This issue is solved using the new URL.

Regards,

Paul Wang
