### ISSUE TITLE
Server Installation Hanging

### ISSUE THREAD

**Issue by KennyYou** [StrongKey/fido2#37]
Hi, after trying to run the installation it continuously hangs on `.grep: /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory` with no resolution. 

`Installing required linux packages (openjdk, unzip, libaio, ncurses-compat-libs[only applicable for Amazon Linux], rng-tools, curl) ... The installer will skip packages that do not apply or are already installed. Failed to restart rngd.service: Unit rngd.service not found.
Successful
Installing StrongKey FIDO2 Server (SKFS) ... Successful
Installing MariaDB... Successful
Installing Payara... Successful
Installing JDBC Driver... Successful
Installing OpenDJ... Successful
Importing default users... Successful
Creating 10M SKFS Internal Database...grep: /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory
.grep: /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory
.grep: /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory
.grep: /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory`

I am running this on Ubuntu 18.04 with system settings here: 
8153528 K total memory
       881912 K used memory
      1913088 K active memory
      4989344 K inactive memory
       904612 K free memory
        65696 K buffer memory
      6301308 K swap cache
       871988 K total swap
            0 K used swap
       871988 K free swap

And my disk space:
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           797M  1.3M  795M   1% /run
/dev/sda1        18G  7.3G  9.4G  44% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0      1.0M  1.0M     0 100% /snap/gnome-logs/81
/dev/loop1       90M   90M     0 100% /snap/core/8268
/dev/loop2       45M   45M     0 100% /snap/gtk-common-themes/1440
/dev/loop3      4.3M  4.3M     0 100% /snap/gnome-calculator/544
/dev/loop4       15M   15M     0 100% /snap/gnome-characters/399
/dev/loop5       92M   92M     0 100% /snap/core/8689
/dev/loop6      3.8M  3.8M     0 100% /snap/gnome-system-monitor/127
/dev/loop7      161M  161M     0 100% /snap/gnome-3-28-1804/116
/dev/loop8       55M   55M     0 100% /snap/core18/1668
tmpfs           797M   32K  797M   1% /run/user/1000

Any help would be appreciated.

**Comment by push2085** [comment]
Hi @KennyYou,
I see a problem during the installation script, 
"Installing required linux packages (openjdk, unzip, libaio, ncurses-compat-libs[only applicable for Amazon Linux], rng-tools, curl) ... The installer will skip packages that do not apply or are already installed. **Failed to restart rngd.service: Unit rngd.service not found**."
This leads me to believe that some packages may not have been installed correctly. 

1) Where is this VM located? is it in one of the cloud provider? or local pc?

2) Does this have the internet access to connect to repositories to execute yum or apt install commands?

Thank you

**Comment by KennyYou** [comment]
Hi @push2085 

1. I've tried on two different platforms one on local (Ubuntu 18.04) and one on cloud (Debian 9) and they both output the same error of: **Failed to restart rngd.service: Unit rngd.service not found**

2. And they both have internet access will having the ability to commit both yum or apt install commands.
