### ISSUE TITLE
FIDO2SimulatorClient

### ISSUE THREAD

**Issue by nikosf95** [StrongKey/fido2#38]
Hello everyone,
I would like to ask if this  https://github.com/StrongKey/fido2/tree/master/server/FIDO2SimulatorClient is some kind of fido2 client or is it part of the code that is running on server?
Thanks in advance

**Comment by push2085** [comment]
Hi @nikosf95,
With this new release, we have added a FIDO simulator that can be used to write tests. FIDOClientSimulator is a standalone java project that has examples on how to use the simulator.

Thank you

**Comment by nikosf95** [comment]
Is there a way to install it and run it? Because i try to use api calls theough postman and i am getting an error that says invalid user svcusername

**Comment by pattycakelol** [comment]
Hi @nikosf95,
Here is a postman collection that I have made and tested that it works.
[SKFS_REST_PASSWORD_AUTH.zip](https://github.com/StrongKey/fido2/files/4277120/SKFS_REST_PASSWORD_AUTH.zip)
Make sure to change the request URL when you are using it.

Could you both of the following:
1. Tail the glassfish server logs and post the output from making a postman request using the above postman collection
2. Tail the OpenDJ logs and post the output from making a postman request using the above postman collection

**Comment by nikosf95** [comment]
Hello @pattycakelol ,
Here is my jdbc access log 
![image](https://user-images.githubusercontent.com/36332126/75709309-1645a180-5ccb-11ea-80fc-7356db621767.png)

and payara server.log 
[server.log](https://github.com/StrongKey/fido2/files/4277442/server.log)
After trying the preregister api call

**Comment by pattycakelol** [comment]
Hi @nikosf95 ,
The skfsclient can be found at: 
/usr/local/strongkey/skfsclient/ 
Documentation on how to use the client can be found at: 
https://github.com/StrongKey/fido2/blob/master/server/skfsclient/skfsclient.md

**Comment by nikosf95** [comment]
@pattycakelol  Thank you so much about the help you providing me. One last question: How can i find out the svcusername and svcpassword to resolve the error about the postman error?

**Comment by DavidCBeach** [comment]
@nikosf95 
'svcfidouser' is the default  svcusername and 'Abcd1234!' is the default svcpassword. According to your server.log there appears to be an issue with LDAP recognizing 'svcfidouser'. 
Please run on your FIDO2 Server:

/usr/local/strongkey/OpenDJ-3.0.0/bin/ldapsearch --port 1389 --baseDN dc=strongauth,dc=com "(&)" cn | grep svcfidouser

and

df 

 Please respond with the results of both commands.

**Comment by techfreak748** [comment]
df result: 
![image](https://user-images.githubusercontent.com/61089423/75729177-ad721f80-5cf2-11ea-9aac-e3ba9ee54cc8.png)

usr/local/strongkey/OpenDJ-3.0.0/bin/ldapsearch --port 1389 --baseDN dc=strongauth,dc=com "(&)" cn | grep svcfidouser  result was empty nothing returned

**Comment by nikosf95** [comment]
df result:
![image](https://user-images.githubusercontent.com/36332126/75730015-3dfd2f80-5cf4-11ea-83c3-1f129bf84335.png)

/usr/local/strongkey/OpenDJ-3.0.0/bin/ldapsearch --port 1389 --baseDN dc=strongauth,dc=com "(&)" cn | grep svcfidouser  returned nothing

**Comment by nikosf95** [comment]
Any suggestions about the previous comment? I haven't manage to resolve the issue.
Thank you in advance

**Comment by pattycakelol** [comment]
Hi @nikosf95,
Did you happen to see any errors during your installation of the FIDO2 Server regarding OpenDJ?
The FIDO2 Server's install script includes the adding of default OpenDJ users (svcfidouser being one of them). To verify this, could you make sure that svcfidouser can be found in your "skce.ldif" in the directory where you extracted the "fido2server-v4.3.0-dist.tgz"

**Comment by nikosf95** [comment]
No i didnt see any errors. The installation was done perfectly. The skce.ldif file i used seems to contain the svcfidouser as it is the same that is uploaded here  https://github.com/StrongKey/fido2/blob/master/server/fidoserverInstall/skce.ldif

Any suggestions please?
