### ISSUE TITLE
Ways to sign up in strongkey test page

### ISSUE THREAD

**Issue by nikosf95** [StrongKey/fido2#44]
Hello everyone,
I would like to ask how can i signup in the official fido 2 test server from my desktop?
I mean i would like to signup, is it possible to do it by using a usb fingerprint scanner?
I could do it from my mobile phone by using my fingerprint scanner but is it possible to do the same on a desktop?
Thanks in advance.

**Comment by max-smyth** [comment]
Hi Niko,

You can use any FIDO U2F or FIDO2 Authenticator to register a key with 
our FIDO2 Server. If your desktop is running Windows 10, you can enable 
Windows Hello and use a biotmetric or PIN to perform local 
authentication to the computer. That in turn will allow Windows 10 to 
register a key with the FIDO2 Server. This works with Edge.

If you have a MacBook with TouchID, you can do the same thing with a 
Chrome browser. With all other browsers, you will need an external 
authenticator to register a key from the desktop.

Hope that helps.

Arshad

**Comment by push2085** [comment]
Hi Niko,

There are FIDO keys available in the market with a fingerprint scanner, 
so If you do want to use an external authenticator with Biometrics, just 
make sure its FIDO enabled and certified.

Thank you,

StrongKey <https://strongkey.com> 	Pushkar Marathe | /Engineering Team 
Lead/

StrongKey <https://strongkey.com>

408.331.2000 <tel:+4083312000>

strongkey.com <https://strongkey.com/>

Cupertino, CA

More information about personal data processing and privacy is available 
here. <https://www.strongkey.com/privacy-policy-terms-of-use/>

**Comment by nikosf95** [comment]
Do i need to have a security key in order to use the skfsclient? Or it just simulates the api calls without a security key?

**Comment by DavidCBeach** [comment]
@nikosf95 The skfsclient uses a simulated FIDO2 authenticator to successfully conduct its API calls. No external FIDO2 security key required.

**Comment by nikosf95** [comment]
So that means it doesn't communicate through api calls with the fido server ?
Sorry for the questions but i am a bit confused

**Comment by pattycakelol** [comment]
Hi @nikosf95,
The skfsclient does make api calls to the FIDO2 Server. The processes of authentication and registration through the FIDO protocol require the use of a security key, which the skfsclient gets around by using the FIDO2 Token Simulator instead.

**Comment by nikosf95** [comment]
That is perfect thank you very much.
