### ISSUE TITLE
Certimport.sh failure

### ISSUE THREAD

**Issue by nikosf95** [StrongKey/fido2#45]
Hello everyone again,
I was trying to use the certimport.sh script, which i hope it is a script for inserting a new certificate to the server and each time i try to get it to work it returns the following error.
![image](https://user-images.githubusercontent.com/36332126/77123391-b1b77000-6a48-11ea-88b1-b92de3bb796d.png)

Any help please?
Thank you in advance.

**Comment by arshadnoor** [comment]
Try using the password "changeit", Niko.

Arshad

**Comment by push2085** [comment]
Hi @nikosf95 ,
Like Arshad mentioned, use the default password "changeit" or just dont use the "-w" option and it will use the default password.

**Comment by nikosf95** [comment]
Hello and thanks for the reply. Changeit worked for me but still i did not manage to import the certificate. I mean it is still an untrusted location

**Comment by arshadnoor** [comment]
This is because, unfortunately, keytool will silently create the 
keystore in whatever location you are executing the command.

Please go to the specific folder where the actual keystore.jks file is 
located and execute the command there - and then confirm using the 
keytool -list command, to confirm that your certificate is in the 
keystore in the correct location.

Assuming you want to import the certificate for the Payara keystore, the 
location is: /usr/local/strongkey/payara41/glassfish/domains/domain1/config.

**Comment by nikosf95** [comment]
Sorry but i didn't understand. What i did was to run the following command 
./certimport.sh FQDN -p8181 -k/usr/local/strongkey/payara41/glassfish/domains/domain1/config/cacerts.jks

**Comment by nikosf95** [comment]
Any help please?

**Comment by push2085** [comment]
Hi @nikosf95 ,
Can you explain a little more on what is untrusted?

The server generates a self signed certificate so its not chained to any trusted CA so the browser will always show a warning if you try to connect to the UI.

Thank you

**Comment by nikosf95** [comment]
When i am getting into the website it says that it may not be trusted and i was wondering if by importing the certificate this becomes a safe site.

**Comment by push2085** [comment]
No Like mentioned above, by default the fido server will generate a self signed certificate and the browser will always prompt a warning.

If you want you can issue a certificate from someone like LetsEncrypt and use it with the FIDO server which will make it trusted but that is out of scope for this installation.

**Comment by nikosf95** [comment]
Oh perfect thanks for the replies.
