### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by derektumulak** [StrongKey/fido2#46]
Opendj is not starting and is causing the installation to fail. I see the following when I run: systemctl status opendj.service

● opendjd.service - LSB: Init script for Opendj
   Loaded: loaded (/etc/init.d/opendjd; generated)
   Active: failed (Result: exit-code) since Thu 2020-03-26 18:29:57 UTC; 5min ag
     Docs: man:systemd-sysv-generator(8)
  Process: 20331 ExecStart=/etc/init.d/opendjd start (code=exited, status=127)

There was another issue that someone else had that closed this out. The solution seemed to be a missing library or dependency but the individual didn't explain what he/she did.

**Comment by pattycakelol** [comment]
Hi @derektumulak,
Could you give us some information about the vm you are using?
Please post the output of the following commands to help us get a better understanding of why this problem may have occurred:
#> df -h
#> vmstat -s | head
Could you also provide the contents of your "/var/log/messages" file?

**Comment by pattycakelol** [comment]
Hi @derektumulak,
Are you still encountering this issue?

**Comment by derektumulak** [comment]
Hi Patrick, thanks for following up. Unfortunately, I haven't continued to
look into this.

Best,
-Derek
