### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by namber1908** [StrongKey/fido2#52]
When i installed the demo basic server, and i try "Register", but the error log show up with the text "SecurityError: This is an invalid domain." 
Which of Error can be here, please help, thank a lot!

**Comment by pattycakelol** [comment]
Hi @namber1908,
Could you give us some information about the vm you are using?
Please post the output of the following commands to help us get a better understanding of why this problem may have occurred:
#> df -h
#> vmstat -s | head
Could you also provide the contents of your "/var/log/messages" file?

**Comment by pattycakelol** [comment]
In addition to this, could you attach a screenshot of your browser when you try to register as well as a screenshot of your browser's console when the error occurs?

**Comment by namber1908** [comment]
Thank for reply back
I found it, I did not set up FQDN as in the installation instructions.
