### ISSUE TITLE
MAVEN Error in Build FIDO SERVER

### ISSUE THREAD

**Issue by superbly** [StrongKey/fido2#59]
I tried to clone the FIDO SERVER code in github and run it on INTELIJ IDE, but an error occurred in Maven. ex) mvn clean package

How can I properly deploy it locally?

my project ↓

![캡처3](https://user-images.githubusercontent.com/40204800/82980492-8e9ad500-a024-11ea-8703-801d7339b2d0.PNG)

maven ↓

![캡처2](https://user-images.githubusercontent.com/40204800/82980556-b38f4800-a024-11ea-89dc-0017b02867f9.PNG)

![캡쳐4](https://user-images.githubusercontent.com/40204800/82980667-ffda8800-a024-11ea-9ef3-02272f59b060.PNG)

![캡처1](https://user-images.githubusercontent.com/40204800/82980675-0537d280-a025-11ea-95d9-b67d3b00242e.PNG)

**Comment by DavidCBeach** [comment]
Hey @superbly 


To build the project you can run these commands in a terminal in the fido2/server directory:


Here is adding the dependencies:

mvn install:install-file "-Dfile=lib/replicationEJB.jar" "-DgroupId=com.strongkey" "-DartifactId=replicationEJB" "-Dversion=4.3.0" "-Dpackaging=jar" "-DgeneratePom=true"
mvn install:install-file "-Dfile=lib/replicationWAR.war" "-DgroupId=com.strongkey" "-DartifactId=replicationWAR" "-Dversion=4.3.0" "-Dpackaging=war" "-DgeneratePom=true"
mvn install:install-file "-Dfile=lib/bc-fips-1.0.1.jar" "-DgroupId=org.bouncycastle" "-DartifactId=bc-fips" "-Dversion=1.0.1" "-Dpackaging=jar" "-DgeneratePom=true"
mvn install:install-file "-Dfile=lib/bcpkix-fips-1.0.0.jar" "-DgroupId=org.bouncycastle" "-DartifactId=bcpkix-fips" "-Dversion=1.0.1" "-Dpackaging=jar" "-DgeneratePom=true"

Here is modifying the pom.xml:

sed -i "s/<module>apiclient<\/module>//g" pom.xml


Here is building the project:

mvn clean install

**Comment by superbly** [comment]
Thank you.
I solved the problem with your answers.
And I have an additional question.
We are testing FIDO SERVER at LOCAL. Is there a way to test it with "localhost" or "ipaddress" instead of FQDN?

**Comment by pattycakelol** [comment]
Hi @superbly,
Glad to hear it worked out for you. 
Unfortunately localhost and ip addresses will not work in place of FQDN, however an easy way to work around this would be to create a hosts file entry for the desired ip address.

SKFE = StrongKey FIDO Engine
SKFS = StrongKey FIDO Server
