### ISSUE TITLE
FIDO2 API problem: send  post but get"401 Unauthorized" response

### ISSUE THREAD

**Issue by s911414** [StrongKey/fido2#6]
Hi,

I follow the API doc. and execute the curl command to send https post to FIDO2 server,
but I always got the "401 Unauthorized" response.
What information should I add into the API request to process the authorization?

BR,
Raymond

**Comment by push2085** [comment]
Hi
can you post the curl request in the comment here?

Also did you set up your own FIDO2 server?

Also the api uses HMAC authentication where you will need to generate HMAC over the POST data as specified in the API doc. 

The properties file for the sample application provides the default access credentials (https://github.com/StrongKey/fido2/blob/master/sampleapps/java/basic/server/src/main/resources/resources/webauthntutorial-configuration.properties)

**Comment by s911414** [comment]
Hi, 
my command is:
curl -X POST "https://fido2.aiotxems.io:8181/api/domains/1/fidokeys/registration/challenge" -H "accept: application/json" -H "strongkey-content-sha256: MjNkZjNiNWM0OTViMGNhNjc1Y2VjZThkM2EyYzQ5NDZlNTQyZDUzNGEzMWI0OWI3NzgxY2QwYzU4ZWY5MzgwZg==" -H "Date:Thu, 09 May 2019 16:48:59 CST" -H "strongkey-api-version: 2.0" -H "Content-Type: application/json" -H "Authorization:HMAC 162a5684336fa6e7:6fX4Ra00OxKUvxv/XjPHN6XAA/h1pK7R18TDnK7QRgU=" -d "{\"protocol\":\"FIDO2_0\",\"username\":\"raymond\",\"displayname\":\"raymond\",\"options\":{},\"extensions\":{}}" --cacert fido2.cert

I use the secrete key and access key in webauthntutorial-configuration.properties to generate the HMAC date, but now always get "HTTP Status 400 - Bad Request"

**Comment by max-smyth** [comment]
Try escaping the double quotations in your body like so
"{\"protocol\":\"FIDO2_0\",\"username\":\"raymond\",\"displayname\":\"raymond\",\"options\":{},\"extensions\":{}}" 

Make sure to recreate the sha and the hmac in the authorization header.

**Comment by s911414** [comment]
Hi max,

After add escape character,
I think the server side parser is OK.

But now I got "HTTP Status 401 - Unauthorized".
Is it the error about HMAC or CA verify?

I use the following self-sign CA file to verify with server:
-----BEGIN CERTIFICATE-----
MIIDFTCCAf2gAwIBAgIEX7a+fjANBgkqhkiG9w0BAQsFADA7MR0wGwYDVQQLExRT
dHJvbmdLZXkgRmlkb1NlcnZlcjEaMBgGA1UEAxMRZmlkbzIuYWlvdHhlbXMuaW8w
HhcNMTkwNTA4MDIwODA4WhcNMjkwMjA2MDIwODA4WjA7MR0wGwYDVQQLExRTdHJv
bmdLZXkgRmlkb1NlcnZlcjEaMBgGA1UEAxMRZmlkbzIuYWlvdHhlbXMuaW8wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDpAqNc0+f2xBLTqIhhNO3yU1sN
dypDikyfDknScOT6iyvXGT1mGYBVTBMSnwQWjCqkHc5v+Odn5ZehA7a9H+F0IHjn
bVarkttPWWnPTMr//7oPgqqPIty71o9Y1dwaty6j7gpKH2EFadyxhNUByL9fg5dK
/2Tu9XT8ZEqe5xLpF1AUJFyEXvOD/8O/b6Goa/2SNngEFx6JVIqrg/pFy0RAifgf
GU/bwPI3992aH0YMAkJE5I6fD0w45dgyGKY6xlGNIpGyCTOpvSzdvQ0/aOkMGHTp
Hi3AYmFDlrDlUyTUPo8OMyieLZ3wJbJkNZuGyvY1VOZHpOkzUpiVY42UZDDRAgMB
AAGjITAfMB0GA1UdDgQWBBSVtADaLRJK4oKOKaRvMPj1a844NTANBgkqhkiG9w0B
AQsFAAOCAQEAGR6Nn/fY0SgE5NQ1zdfhtqlmd1yF1VuYo/cgVsH+jQuapD/qxZIl
rKB9hfjyeKdu1t2yXqw0LwwYSDGdFJW33pCuJ+9/rEhg3p1w/Vifbz9oH1RFU/VN
jIpwn9NkAY4X1lunKqOTZnGCdBr1h031vH5DOiJjilseWpkNK9/mG9pfT9/fDKrs
7gd2qcAt7BfP2a2g2PhY8uD4qxVEJbIRH3IfKXClIpBtutsV7z7efBXbit92fVbC
sFg8jUCdkJmTKCa8bW3Ygyua9BOLBkgINNlftYSCgTBDOMHx+N4H2AxFbSasAuOc
yt93fbTF0fHjYi9+gb4Bgxlxhp7ealGxMw==
-----END CERTIFICATE-----

**Comment by max-smyth** [comment]
So, your problem is in the hmac, or maybe even the sha calculation. Here is the curl arguments we used which worked:

-H "accept: application/json"
-H "strongkey-content-sha256: HMiUyf941hPZWj/Z3u6ezAnk092VBwuACdp/3ZC9EJQ="
-H "Date:Thu, 09 May 2019 16:48:59 CST"
-H "strongkey-api-version: 2.0"
-H "Content-Type: application/json"
-H "Authorization:HMAC 162a5684336fa6e7:8EgEFlaS1P7TK/eNm/UliwqgxdY9+fp2cF2tivCgeiE="
-d '{"protocol":"FIDO2_0","username":"raymond","displayname":"raymond","options":"{}","extensions":"{}"}'

You should see that your sha256 and hmac that you are calculating end up matching what we got.

**Comment by push2085** [comment]
Hi @s911414 ,
Is your issue resolved? There has not been any activity for almost a month and we will close this issue next week.

**Comment by s911414** [comment]
Hi @push2085 ,
I resolved this issue, thanks :)
