### ISSUE TITLE
fido_users table has invalid primary key for mysql 5.7

### ISSUE THREAD

**Issue by segevmalool** [StrongKey/fido2#77]
When applying data definitions using mysql 5.7, the primary key for fido_users table is invalid because all primary key components cannot be null:

```
All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```

To reproduce, try to create the fido_users table in mysql 5.7.

This was observed on OSX running mysql 5.7 installed with homebrew.

**Comment by push2085** [comment]
Hi @segevmalool ,
Thank you for bringing it to our attention, we will get this fixed and upload a new version.
