### ISSUE TITLE
Error in registering a new user/key from mobile devices

### ISSUE THREAD

**Issue by vishikgarg** [StrongKey/fido2#79]
StrongKey demo app hosted at "https://demo4.strongkey.com:8181/basicserver" works fine on MacOS for registration and authentication flow, however, it does not work from mobile devices iOS and Android. I get the following error message: WEBAUTHN-WS-ERR-1000: An unexpected error occurred. Please check server logs for details

**To Reproduce**
1. Go to https://demo4.strongkey.com:8181/basicserver
2. Click on Register.
3. Enter username and Key display name.
4. Click on "Register New Key".
5. A pop up is displayed asking to use the security key or face ID.
6. Click on "Use Face ID".
7. FaceID is verified by iPhone.
8. You get the error message "WEBAUTHN-WS-ERR-1000: An unexpected error occurred. Please check server logs for details".

**Expected behavior**
The user should be registered successfully and a success message should be shown to the user.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.2
 - Browser - Safari
 - Version - Safari 14

**Additional context**

**Comment by vishikgarg** [comment]
Error screenshot

![StrongKeyError](https://user-images.githubusercontent.com/16101195/102221999-dd4c8580-3f08-11eb-8225-46c0a4e01ef8.jpeg)

**Comment by push2085** [comment]
Hi @vishikgarg ,
Our Current server on github is based on the webauthn Level 1 specificcation which did not include the apple attestation format and so Ios devices will not work if you use safari browser with platform authenticators (touch or face Id). If you do have an external security key then you can use that over NFC or even USB C and it should work.

**Comment by vishikgarg** [comment]
Hi @push2085 ,

Do you have plans to support the latest webAuthn specification soon? or the platform authenticators (iOS and Android) already work with the enterprise version of SKFS?
Please note that I saw the same error when trying to use the Android platform authenticator.

Regards
Vishik

**Comment by arshadnoor** [comment]
Hi Vishik,

The Android platform authenticator already works with our FIDO server as 
long as you are using Chrome and you have a Google Play Services account 
setup. They used to require the Google Authenticator app also to be 
installed on the phone, but I think they may have removed that 
restriction. If you meet the first 2 constraints but it is still not 
working on your phone, try it again after installing the Google 
Authenticator app.

We will definitely be working on the new spec; we're waiting for it to 
be finalized and voted on by the W3C - there are still many open issues 
at the W3C on the WebAuthn list, and we're particularly interested in at 
least one of them (https://github.com/w3c/webauthn/issues/1522) to see 
what decision the working group makes.

Arshad
