### ISSUE TITLE
Validate hmac-secret extension for offline authentication

### ISSUE THREAD

**Issue by jeorgearomal** [StrongKey/fido2#80]
Hi Team,

 
I followed the steps provided in the below url and I was able to successfully add a security token and validate it.
https://github.com/StrongKey/fido2/blob/master/tutorial/node/SKFS_Tutorial.md

 
My security token supports hmac-secret extension. Can you please provide instructions on how to validate hmac-secret extension for offline authentication

**Comment by push2085** [comment]
Hi @jeorgearomal ,
If you are looking for the extensions defined in the webauthn specification, the current version of FIDOServer does not support them.
