### ISSUE TITLE
Error /usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory while installing fido2 server

### ISSUE THREAD

**Issue by phungtiep** [StrongKey/fido2#88]
While I am installing FIDO2 server on Ubuntu 18.04.5 LTS, i have got this error with LOOP:
/usr/local/strongkey/mariadb-10.2.30/log/mysqld-error.log: No such file or directory
How can i solve it?

**Comment by F9Alejandro** [comment]
Typically that means that the file doesn't exist and it will be created for you. However it could be that the directory structure is missing, I would do a reinstall via `sudo ./cleanup.sh` possibly also delete the zip files that are downloaded so they will have a fresh download and install.
